### PR TITLE
Several improvements

### PR DESCRIPTION
**Pull request by mheinzler**
These are some improvements I made to use the linter with my projects. Mainly this is removal of deprecated code and improving warnings and errors.

### CODE REVIEW

**Comment by rwols** [comment]
Looks good to me!

**Comment by mheinzler** [comment]
Hi Raoul,
thanks! If you don't mind I will add a new version tag to make it available on Package Control.

**Comment by rwols** [comment]
I'm already on that, have some patience :P

**Comment by rwols** [comment]
I've released 1.1.0 with your changes. I've also given you commit access as you've noticed. You can find me on the sublime text discord channel if you want to discuss anything: https://forum.sublimetext.com/t/sublime-text-discord-server/26063

**Pull request merged**
